~samples.putPairs([
    "viola.arco", Dictionary.newFrom([
        "mf", Dictionary.newFrom([
            "c", Dictionary.newFrom([
                "48", Dictionary.newFrom([
                    "midi", "48", "duration", 3.6848526077097508, "frames", 162502, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.48.Viola.arco.sulC.mf.C3B3.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.48.Viola.arco.sulC.mf.C3B3.mono.wav").fullPath), "loop_points", List[
                        [37078, 43491, ],
                    ],
                ]), "63", Dictionary.newFrom([
                    "midi", "63", "duration", 2.973673469387755, "frames", 131139, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.63.Viola.arco.sulC.mf.C4C5.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.63.Viola.arco.sulC.mf.C4C5.mono.wav").fullPath), "loop_points", List[
                        [53676, 54812, ], [62210, 64765, ], [75499, 76633, ],
                    ],
                ]), "49", Dictionary.newFrom([
                    "midi", "49", "duration", 2.5288662131519275, "frames", 111523, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.49.Viola.arco.sulC.mf.C3B3.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.49.Viola.arco.sulC.mf.C3B3.mono.wav").fullPath), "loop_points", List[
                        [39020, 44118, ], [57837, 62937, ], [58466, 63566, ],
                    ],
                ]), "56", Dictionary.newFrom([
                    "midi", "56", "duration", 3.6926303854875284, "frames", 162845, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.56.Viola.arco.sulC.mf.C3B3.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.56.Viola.arco.sulC.mf.C3B3.mono.wav").fullPath), "loop_points", List[
                        [62938, 66948, ],
                    ],
                ]), "60", Dictionary.newFrom([
                    "midi", "60", "duration", 4.327619047619048, "frames", 190848, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.60.Viola.arco.sulC.mf.C4C5.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.60.Viola.arco.sulC.mf.C4C5.mono.wav").fullPath), "loop_points", List[
                        [106629, 112839, ], [107283, 113492, ],
                    ],
                ]), "66", Dictionary.newFrom([
                    "midi", "66", "duration", 2.9431065759637187, "frames", 129791, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.66.Viola.arco.sulC.mf.C4C5.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.66.Viola.arco.sulC.mf.C4C5.mono.wav").fullPath), "loop_points", List[
                        [83605, 88015, ],
                    ],
                ]), "50", Dictionary.newFrom([
                    "midi", "50", "duration", 3.245328798185941, "frames", 143119, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.50.Viola.arco.sulC.mf.C3B3.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.50.Viola.arco.sulC.mf.C3B3.mono.wav").fullPath), "loop_points", List[
                        [43017, 48127, ], [43588, 48698, ], [57378, 62787, ],
                    ],
                ]), "51", Dictionary.newFrom([
                    "midi", "51", "duration", 2.987936507936508, "frames", 131768, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.51.Viola.arco.sulC.mf.C3B3.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.51.Viola.arco.sulC.mf.C3B3.mono.wav").fullPath), "loop_points", List[
                        [58800, 64462, ],
                    ],
                ]), "57", Dictionary.newFrom([
                    "midi", "57", "duration", 3.585827664399093, "frames", 158135, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.57.Viola.arco.sulC.mf.C3B3.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.57.Viola.arco.sulC.mf.C3B3.mono.wav").fullPath), "loop_points", List[
                        [92727, 100761, ], [92929, 100964, ],
                    ],
                ]), "61", Dictionary.newFrom([
                    "midi", "61", "duration", 3.404512471655329, "frames", 150139, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.61.Viola.arco.sulC.mf.C4C5.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.61.Viola.arco.sulC.mf.C4C5.mono.wav").fullPath), "loop_points", List[
                        [80409, 85332, ],
                    ],
                ]), "64", Dictionary.newFrom([
                    "midi", "64", "duration", 2.891541950113379, "frames", 127517, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.64.Viola.arco.sulC.mf.C4C5.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.64.Viola.arco.sulC.mf.C4C5.mono.wav").fullPath), "loop_points", List[
                        [68853, 73806, ],
                    ],
                ]), "69", Dictionary.newFrom([
                    "midi", "69", "duration", 2.607233560090703, "frames", 114979, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.69.Viola.arco.sulC.mf.C4C5.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.69.Viola.arco.sulC.mf.C4C5.mono.wav").fullPath), "loop_points", List[
                        [33572, 34982, ],
                    ],
                ]), "52", Dictionary.newFrom([
                    "midi", "52", "duration", 3.2371655328798186, "frames", 142759, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.52.Viola.arco.sulC.mf.C3B3.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.52.Viola.arco.sulC.mf.C3B3.mono.wav").fullPath), "loop_points", List[
                        [63289, 69715, ],
                    ],
                ]), "67", Dictionary.newFrom([
                    "midi", "67", "duration", 3.0173242630385486, "frames", 133064, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.67.Viola.arco.sulC.mf.C4C5.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.67.Viola.arco.sulC.mf.C4C5.mono.wav").fullPath), "loop_points", List[
                        [29692, 31929, ],
                    ],
                ]), "53", Dictionary.newFrom([
                    "midi", "53", "duration", 3.055986394557823, "frames", 134769, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.53.Viola.arco.sulC.mf.C3B3.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.53.Viola.arco.sulC.mf.C3B3.mono.wav").fullPath), "loop_points", List[
                        [49743, 56819, ],
                    ],
                ]), "58", Dictionary.newFrom([
                    "midi", "58", "duration", 3.3662585034013603, "frames", 148452, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.58.Viola.arco.sulC.mf.C4C5.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.58.Viola.arco.sulC.mf.C4C5.mono.wav").fullPath), "loop_points", List[
                        [71331, 76068, ], [83648, 89521, ],
                    ],
                ]), "62", Dictionary.newFrom([
                    "midi", "62", "duration", 5.274399092970522, "frames", 232601, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.62.Viola.arco.sulC.mf.C4C5.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.62.Viola.arco.sulC.mf.C4C5.mono.wav").fullPath), "loop_points", List[
                        [103284, 105841, ],
                    ],
                ]), "54", Dictionary.newFrom([
                    "midi", "54", "duration", 3.2449206349206348, "frames", 143101, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.54.Viola.arco.sulC.mf.C3B3.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.54.Viola.arco.sulC.mf.C3B3.mono.wav").fullPath), "loop_points", List[
                        [65147, 72056, ],
                    ],
                ]), "65", Dictionary.newFrom([
                    "midi", "65", "duration", 2.7718367346938777, "frames", 122238, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.65.Viola.arco.sulC.mf.C4C5.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.65.Viola.arco.sulC.mf.C4C5.mono.wav").fullPath), "loop_points", List[
                        [36918, 41970, ],
                    ],
                ]), "55", Dictionary.newFrom([
                    "midi", "55", "duration", 3.739251700680272, "frames", 164901, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.55.Viola.arco.sulC.mf.C3B3.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.55.Viola.arco.sulC.mf.C3B3.mono.wav").fullPath), "loop_points", List[
                        [47040, 52217, ],
                    ],
                ]), "59", Dictionary.newFrom([
                    "midi", "59", "duration", 3.2822675736961453, "frames", 144748, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.59.Viola.arco.sulC.mf.C4C5.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.59.Viola.arco.sulC.mf.C4C5.mono.wav").fullPath), "loop_points", List[
                        [77540, 82701, ],
                    ],
                ]), "68", Dictionary.newFrom([
                    "midi", "68", "duration", 3.442857142857143, "frames", 151830, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.68.Viola.arco.sulC.mf.C4C5.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.68.Viola.arco.sulC.mf.C4C5.mono.wav").fullPath), "loop_points", List[
                        [50527, 52431, ], [65293, 66455, ],
                    ],
                ]), "70", Dictionary.newFrom([
                    "midi", "70", "duration", 2.6698866213151926, "frames", 117742, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.70.Viola.arco.sulC.mf.C4C5.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.70.Viola.arco.sulC.mf.C4C5.mono.wav").fullPath), "loop_points", List[
                        [61283, 64423, ],
                    ],
                ]),
            ]), "g", Dictionary.newFrom([
                "55", Dictionary.newFrom([
                    "midi", "55", "duration", 5.832063492063492, "frames", 257194, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.55.Viola.arco.sulG.mf.G3B3.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.55.Viola.arco.sulG.mf.G3B3.mono.wav").fullPath), "loop_points", List[
                        [49379, 56804, ],
                    ],
                ]), "59", Dictionary.newFrom([
                    "midi", "59", "duration", 3.1571201814058956, "frames", 139229, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.59.Viola.arco.sulG.mf.G3B3.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.59.Viola.arco.sulG.mf.G3B3.mono.wav").fullPath), "loop_points", List[
                        [31045, 36418, ],
                    ],
                ]), "65", Dictionary.newFrom([
                    "midi", "65", "duration", 2.793718820861678, "frames", 123203, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.65.Viola.arco.sulG.mf.C4B4.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.65.Viola.arco.sulG.mf.C4B4.mono.wav").fullPath), "loop_points", List[
                        [45199, 49124, ],
                    ],
                ]), "72", Dictionary.newFrom([
                    "midi", "72", "duration", 2.9192290249433106, "frames", 128738, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.72.Viola.arco.sulG.mf.C5G5.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.72.Viola.arco.sulG.mf.C5G5.mono.wav").fullPath), "loop_points", List[
                        [47773, 49288, ],
                    ],
                ]), "68", Dictionary.newFrom([
                    "midi", "68", "duration", 2.5844897959183672, "frames", 113976, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.68.Viola.arco.sulG.mf.C4B4.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.68.Viola.arco.sulG.mf.C4B4.mono.wav").fullPath), "loop_points", List[
                        [38619, 42743, ], [38724, 42847, ], [38831, 42955, ], [39042, 43167, ], [39149, 43273, ], [39255, 43379, ],
                    ],
                ]), "70", Dictionary.newFrom([
                    "midi", "70", "duration", 2.8925396825396827, "frames", 127561, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.70.Viola.arco.sulG.mf.C4B4.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.70.Viola.arco.sulG.mf.C4B4.mono.wav").fullPath), "loop_points", List[
                        [42390, 43993, ],
                    ],
                ]), "75", Dictionary.newFrom([
                    "midi", "75", "duration", 2.885442176870748, "frames", 127248, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.75.Viola.arco.sulG.mf.C5G5.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.75.Viola.arco.sulG.mf.C5G5.mono.wav").fullPath), "loop_points", List[
                        [35153, 37986, ],
                    ],
                ]), "56", Dictionary.newFrom([
                    "midi", "56", "duration", 2.792222222222222, "frames", 123137, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.56.Viola.arco.sulG.mf.G3B3.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.56.Viola.arco.sulG.mf.G3B3.mono.wav").fullPath), "loop_points", List[
                        [32231, 36914, ],
                    ],
                ]), "60", Dictionary.newFrom([
                    "midi", "60", "duration", 3.715328798185941, "frames", 163846, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.60.Viola.arco.sulG.mf.C4B4.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.60.Viola.arco.sulG.mf.C4B4.mono.wav").fullPath), "loop_points", List[
                        [64763, 71162, ], [65605, 72004, ],
                    ],
                ]), "63", Dictionary.newFrom([
                    "midi", "63", "duration", 3.082154195011338, "frames", 135923, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.63.Viola.arco.sulG.mf.C4B4.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.63.Viola.arco.sulG.mf.C4B4.mono.wav").fullPath), "loop_points", List[
                        [34366, 40049, ], [34500, 40183, ],
                    ],
                ]), "78", Dictionary.newFrom([
                    "midi", "78", "duration", 3.1722448979591835, "frames", 139896, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.78.Viola.arco.sulG.mf.C5G5.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.78.Viola.arco.sulG.mf.C5G5.mono.wav").fullPath), "loop_points", List[
                        [66704, 69148, ],
                    ],
                ]), "66", Dictionary.newFrom([
                    "midi", "66", "duration", 2.639410430839002, "frames", 116398, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.66.Viola.arco.sulG.mf.C4B4.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.66.Viola.arco.sulG.mf.C4B4.mono.wav").fullPath), "loop_points", List[
                        [32772, 37544, ],
                    ],
                ]), "73", Dictionary.newFrom([
                    "midi", "73", "duration", 2.5605895691609977, "frames", 112922, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.73.Viola.arco.sulG.mf.C5G5.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.73.Viola.arco.sulG.mf.C5G5.mono.wav").fullPath), "loop_points", List[
                        [80360, 83690, ],
                    ],
                ]), "57", Dictionary.newFrom([
                    "midi", "57", "duration", 2.851746031746032, "frames", 125762, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.57.Viola.arco.sulG.mf.G3B3.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.57.Viola.arco.sulG.mf.G3B3.mono.wav").fullPath), "loop_points", List[
                        [54832, 57040, ],
                    ],
                ]), "61", Dictionary.newFrom([
                    "midi", "61", "duration", 2.914285714285714, "frames", 128520, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.61.Viola.arco.sulG.mf.C4B4.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.61.Viola.arco.sulG.mf.C4B4.mono.wav").fullPath), "loop_points", List[
                        [54023, 60393, ], [54475, 60846, ], [55436, 61806, ], [55754, 62125, ], [55836, 62207, ],
                    ],
                ]), "76", Dictionary.newFrom([
                    "midi", "76", "duration", 3.013673469387755, "frames", 132903, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.76.Viola.arco.sulG.mf.C5G5.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.76.Viola.arco.sulG.mf.C5G5.mono.wav").fullPath), "loop_points", List[
                        [27116, 29118, ],
                    ],
                ]), "71", Dictionary.newFrom([
                    "midi", "71", "duration", 3.1053061224489795, "frames", 136944, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.71.Viola.arco.sulG.mf.C4B4.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.71.Viola.arco.sulG.mf.C4B4.mono.wav").fullPath), "loop_points", List[
                        [57511, 61846, ],
                    ],
                ]), "64", Dictionary.newFrom([
                    "midi", "64", "duration", 2.976326530612245, "frames", 131256, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.64.Viola.arco.sulG.mf.C4B4.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.64.Viola.arco.sulG.mf.C4B4.mono.wav").fullPath), "loop_points", List[
                        [52688, 57237, ],
                    ],
                ]), "69", Dictionary.newFrom([
                    "midi", "69", "duration", 3.5274603174603176, "frames", 155561, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.69.Viola.arco.sulG.mf.C4B4.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.69.Viola.arco.sulG.mf.C4B4.mono.wav").fullPath), "loop_points", List[
                        [60786, 62086, ],
                    ],
                ]), "79", Dictionary.newFrom([
                    "midi", "79", "duration", 3.050498866213152, "frames", 134527, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.79.Viola.arco.sulG.mf.C5G5.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.79.Viola.arco.sulG.mf.C5G5.mono.wav").fullPath), "loop_points", List[
                        [41877, 42717, ],
                    ],
                ]), "58", Dictionary.newFrom([
                    "midi", "58", "duration", 3.3603628117913833, "frames", 148192, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.58.Viola.arco.sulG.mf.G3B3.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.58.Viola.arco.sulG.mf.G3B3.mono.wav").fullPath), "loop_points", List[
                        [39280, 45531, ],
                    ],
                ]), "67", Dictionary.newFrom([
                    "midi", "67", "duration", 3.0266439909297054, "frames", 133475, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.67.Viola.arco.sulG.mf.C4B4.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.67.Viola.arco.sulG.mf.C4B4.mono.wav").fullPath), "loop_points", List[
                        [31859, 35116, ],
                    ],
                ]), "74", Dictionary.newFrom([
                    "midi", "74", "duration", 2.9381179138321993, "frames", 129571, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.74.Viola.arco.sulG.mf.C5G5.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.74.Viola.arco.sulG.mf.C5G5.mono.wav").fullPath), "loop_points", List[
                        [40245, 42785, ],
                    ],
                ]), "62", Dictionary.newFrom([
                    "midi", "62", "duration", 2.8431972789115645, "frames", 125385, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.62.Viola.arco.sulG.mf.C4B4.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.62.Viola.arco.sulG.mf.C4B4.mono.wav").fullPath), "loop_points", List[
                        [59619, 65015, ],
                    ],
                ]), "77", Dictionary.newFrom([
                    "midi", "77", "duration", 3.070861678004535, "frames", 135425, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.77.Viola.arco.sulG.mf.C5G5.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.77.Viola.arco.sulG.mf.C5G5.mono.wav").fullPath), "loop_points", List[
                        [76815, 78640, ],
                    ],
                ]),
            ]), "d", Dictionary.newFrom([
                "68", Dictionary.newFrom([
                    "midi", "68", "duration", 2.9050113378684808, "frames", 128111, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.68.Viola.arco.sulD.mf.D4B4.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.68.Viola.arco.sulD.mf.D4B4.mono.wav").fullPath), "loop_points", List[
                        [71069, 74570, ],
                    ],
                ]), "70", Dictionary.newFrom([
                    "midi", "70", "duration", 3.001360544217687, "frames", 132360, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.70.Viola.arco.sulD.mf.D4B4.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.70.Viola.arco.sulD.mf.D4B4.mono.wav").fullPath), "loop_points", List[
                        [52038, 55917, ],
                    ],
                ]), "75", Dictionary.newFrom([
                    "midi", "75", "duration", 2.9191156462585033, "frames", 128733, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.75.Viola.arco.sulD.mf.C5B5.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.75.Viola.arco.sulD.mf.C5B5.mono.wav").fullPath), "loop_points", List[
                        [48364, 50700, ], [48931, 51054, ],
                    ],
                ]), "63", Dictionary.newFrom([
                    "midi", "63", "duration", 2.91859410430839, "frames", 128710, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.63.Viola.arco.sulD.mf.D4B4.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.63.Viola.arco.sulD.mf.D4B4.mono.wav").fullPath), "loop_points", List[
                        [61789, 66893, ],
                    ],
                ]), "78", Dictionary.newFrom([
                    "midi", "78", "duration", 3.021360544217687, "frames", 133242, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.78.Viola.arco.sulD.mf.C5B5.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.78.Viola.arco.sulD.mf.C5B5.mono.wav").fullPath), "loop_points", List[
                        [40129, 42452, ],
                    ],
                ]), "81", Dictionary.newFrom([
                    "midi", "81", "duration", 3.0515419501133785, "frames", 134573, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.81.Viola.arco.sulD.mf.C5B5.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.81.Viola.arco.sulD.mf.C5B5.mono.wav").fullPath), "loop_points", List[
                        [59459, 61467, ],
                    ],
                ]), "85", Dictionary.newFrom([
                    "midi", "85", "duration", 2.87437641723356, "frames", 126760, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.85.Viola.arco.sulD.mf.C6D6.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.85.Viola.arco.sulD.mf.C6D6.mono.wav").fullPath), "loop_points", List[
                        [87835, 89029, ],
                    ],
                ]), "66", Dictionary.newFrom([
                    "midi", "66", "duration", 3.7200226757369617, "frames", 164053, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.66.Viola.arco.sulD.mf.D4B4.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.66.Viola.arco.sulD.mf.D4B4.mono.wav").fullPath), "loop_points", List[
                        [50602, 55025, ],
                    ],
                ]), "73", Dictionary.newFrom([
                    "midi", "73", "duration", 3.3878231292517005, "frames", 149403, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.73.Viola.arco.sulD.mf.C5B5.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.73.Viola.arco.sulD.mf.C5B5.mono.wav").fullPath), "loop_points", List[
                        [42349, 45523, ],
                    ],
                ]), "76", Dictionary.newFrom([
                    "midi", "76", "duration", 3.2124489795918367, "frames", 141669, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.76.Viola.arco.sulD.mf.C5B5.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.76.Viola.arco.sulD.mf.C5B5.mono.wav").fullPath), "loop_points", List[
                        [41845, 44320, ],
                    ],
                ]), "82", Dictionary.newFrom([
                    "midi", "82", "duration", 2.5763265306122447, "frames", 113616, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.82.Viola.arco.sulD.mf.C5B5.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.82.Viola.arco.sulD.mf.C5B5.mono.wav").fullPath), "loop_points", List[
                        [30117, 34307, ], [41751, 43776, ],
                    ],
                ]), "86", Dictionary.newFrom([
                    "midi", "86", "duration", 3.1915873015873015, "frames", 140749, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.86.Viola.arco.sulD.mf.C6D6.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.86.Viola.arco.sulD.mf.C6D6.mono.wav").fullPath), "loop_points", List[
                        [62865, 63390, ], [62865, 63390, ],
                    ],
                ]), "71", Dictionary.newFrom([
                    "midi", "71", "duration", 3.018049886621315, "frames", 133096, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.71.Viola.arco.sulD.mf.D4B4.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.71.Viola.arco.sulD.mf.D4B4.mono.wav").fullPath), "loop_points", List[
                        [65512, 68632, ],
                    ],
                ]), "64", Dictionary.newFrom([
                    "midi", "64", "duration", 3.0970068027210886, "frames", 136578, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.64.Viola.arco.sulD.mf.D4B4.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.64.Viola.arco.sulD.mf.D4B4.mono.wav").fullPath), "loop_points", List[
                        [35410, 38891, ], [37402, 40883, ],
                    ],
                ]), "69", Dictionary.newFrom([
                    "midi", "69", "duration", 3.237142857142857, "frames", 142758, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.69.Viola.arco.sulD.mf.D4B4.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.69.Viola.arco.sulD.mf.D4B4.mono.wav").fullPath), "loop_points", List[
                        [57511, 61521, ], [74898, 78906, ], [79407, 83415, ],
                    ],
                ]), "79", Dictionary.newFrom([
                    "midi", "79", "duration", 3.0505668934240364, "frames", 134530, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.79.Viola.arco.sulD.mf.C5B5.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.79.Viola.arco.sulD.mf.C5B5.mono.wav").fullPath), "loop_points", List[
                        [41190, 42480, ],
                    ],
                ]), "67", Dictionary.newFrom([
                    "midi", "67", "duration", 4.352721088435374, "frames", 191955, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.67.Viola.arco.sulD.mf.D4B4.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.67.Viola.arco.sulD.mf.D4B4.mono.wav").fullPath), "loop_points", List[
                        [55607, 59215, ],
                    ],
                ]), "74", Dictionary.newFrom([
                    "midi", "74", "duration", 3.290408163265306, "frames", 145107, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.74.Viola.arco.sulD.mf.C5B5.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.74.Viola.arco.sulD.mf.C5B5.mono.wav").fullPath), "loop_points", List[
                        [71358, 72934, ],
                    ],
                ]), "83", Dictionary.newFrom([
                    "midi", "83", "duration", 2.5705668934240364, "frames", 113362, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.83.Viola.arco.sulD.mf.C5B5.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.83.Viola.arco.sulD.mf.C5B5.mono.wav").fullPath), "loop_points", List[
                        [75864, 77116, ],
                    ],
                ]), "62", Dictionary.newFrom([
                    "midi", "62", "duration", 3.8465079365079364, "frames", 169631, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.62.Viola.arco.sulD.mf.D4B4.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.62.Viola.arco.sulD.mf.D4B4.mono.wav").fullPath), "loop_points", List[
                        [47846, 50698, ],
                    ],
                ]), "77", Dictionary.newFrom([
                    "midi", "77", "duration", 3.2990476190476192, "frames", 145488, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.77.Viola.arco.sulD.mf.C5B5.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.77.Viola.arco.sulD.mf.C5B5.mono.wav").fullPath), "loop_points", List[
                        [80667, 82817, ],
                    ],
                ]), "65", Dictionary.newFrom([
                    "midi", "65", "duration", 3.1354195011337866, "frames", 138272, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.65.Viola.arco.sulD.mf.D4B4.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.65.Viola.arco.sulD.mf.D4B4.mono.wav").fullPath), "loop_points", List[
                        [50811, 54102, ],
                    ],
                ]), "72", Dictionary.newFrom([
                    "midi", "72", "duration", 3.5507482993197277, "frames", 156588, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.72.Viola.arco.sulD.mf.C5B5.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.72.Viola.arco.sulD.mf.C5B5.mono.wav").fullPath), "loop_points", List[
                        [51467, 52733, ],
                    ],
                ]), "80", Dictionary.newFrom([
                    "midi", "80", "duration", 3.1149886621315193, "frames", 137371, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.80.Viola.arco.sulD.mf.C5B5.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.80.Viola.arco.sulD.mf.C5B5.mono.wav").fullPath), "loop_points", List[
                        [76888, 78108, ],
                    ],
                ]), "84", Dictionary.newFrom([
                    "midi", "84", "duration", 2.9744444444444444, "frames", 131173, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.84.Viola.arco.sulD.mf.C6D6.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.84.Viola.arco.sulD.mf.C6D6.mono.wav").fullPath), "loop_points", List[
                        [23348, 24524, ],
                    ],
                ]),
            ]), "a", Dictionary.newFrom([
                "78", Dictionary.newFrom([
                    "midi", "78", "duration", 3.786984126984127, "frames", 167006, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.78.Viola.arco.sulA.mf.C5B5.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.78.Viola.arco.sulA.mf.C5B5.mono.wav").fullPath), "loop_points", List[
                        [111816, 114196, ],
                    ],
                ]), "81", Dictionary.newFrom([
                    "midi", "81", "duration", 3.447619047619048, "frames", 152040, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.81.Viola.arco.sulA.mf.C5B5.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.81.Viola.arco.sulA.mf.C5B5.mono.wav").fullPath), "loop_points", List[
                        [60494, 62450, ],
                    ],
                ]), "85", Dictionary.newFrom([
                    "midi", "85", "duration", 3.591768707482993, "frames", 158397, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.85.Viola.arco.sulA.mf.C6A6.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.85.Viola.arco.sulA.mf.C6A6.mono.wav").fullPath), "loop_points", List[
                        [41500, 42969, ],
                    ],
                ]), "91", Dictionary.newFrom([
                    "midi", "91", "duration", 2.57124716553288, "frames", 113392, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.91.Viola.arco.sulA.mf.C6A6.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.91.Viola.arco.sulA.mf.C6A6.mono.wav").fullPath), "loop_points", List[
                        [26455, 29325, ],
                    ],
                ]), "73", Dictionary.newFrom([
                    "midi", "73", "duration", 3.4623356009070294, "frames", 152689, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.73.Viola.arco.sulA.mf.C5B5.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.73.Viola.arco.sulA.mf.C5B5.mono.wav").fullPath), "loop_points", List[
                        [99010, 102187, ],
                    ],
                ]), "92", Dictionary.newFrom([
                    "midi", "92", "duration", 3.0644444444444443, "frames", 135142, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.92.Viola.arco.sulA.mf.C6A6.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.92.Viola.arco.sulA.mf.C6A6.mono.wav").fullPath), "loop_points", List[
                        [62017, 64412, ], [62017, 64412, ],
                    ],
                ]), "69", Dictionary.newFrom([
                    "midi", "69", "duration", 3.7757596371882087, "frames", 166511, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.69.Viola.arco.sulA.mf.A4B4.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.69.Viola.arco.sulA.mf.A4B4.mono.wav").fullPath), "loop_points", List[
                        [76167, 80988, ], [84102, 88119, ], [84604, 88621, ], [92236, 96252, ],
                    ],
                ]), "71", Dictionary.newFrom([
                    "midi", "71", "duration", 3.274580498866213, "frames", 144409, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.71.Viola.arco.sulA.mf.A4B4.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.71.Viola.arco.sulA.mf.A4B4.mono.wav").fullPath), "loop_points", List[
                        [79917, 83396, ],
                    ],
                ]), "76", Dictionary.newFrom([
                    "midi", "76", "duration", 3.741111111111111, "frames", 164983, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.76.Viola.arco.sulA.mf.C5B5.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.76.Viola.arco.sulA.mf.C5B5.mono.wav").fullPath), "loop_points", List[
                        [55671, 58343, ], [75794, 78468, ],
                    ],
                ]), "82", Dictionary.newFrom([
                    "midi", "82", "duration", 3.271224489795918, "frames", 144261, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.82.Viola.arco.sulA.mf.C5B5.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.82.Viola.arco.sulA.mf.C5B5.mono.wav").fullPath), "loop_points", List[
                        [71322, 74485, ],
                    ],
                ]), "86", Dictionary.newFrom([
                    "midi", "86", "duration", 3.1187301587301586, "frames", 137536, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.86.Viola.arco.sulA.mf.C6A6.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.86.Viola.arco.sulA.mf.C6A6.mono.wav").fullPath), "loop_points", List[
                        [78077, 79583, ], [83782, 85287, ],
                    ],
                ]), "93", Dictionary.newFrom([
                    "midi", "93", "duration", 3.207120181405896, "frames", 141434, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.93.Viola.arco.sulA.mf.C6A6.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.93.Viola.arco.sulA.mf.C6A6.mono.wav").fullPath), "loop_points", List[
                        [41555, 42129, ],
                    ],
                ]), "79", Dictionary.newFrom([
                    "midi", "79", "duration", 3.9077097505668936, "frames", 172330, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.79.Viola.arco.sulA.mf.C5B5.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.79.Viola.arco.sulA.mf.C5B5.mono.wav").fullPath), "loop_points", List[
                        [34325, 35281, ],
                    ],
                ]), "74", Dictionary.newFrom([
                    "midi", "74", "duration", 3.086734693877551, "frames", 136125, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.74.Viola.arco.sulA.mf.C5B5.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.74.Viola.arco.sulA.mf.C5B5.mono.wav").fullPath), "loop_points", List[
                        [47875, 51331, ],
                    ],
                ]), "83", Dictionary.newFrom([
                    "midi", "83", "duration", 3.335986394557823, "frames", 147117, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.83.Viola.arco.sulA.mf.C5B5.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.83.Viola.arco.sulA.mf.C5B5.mono.wav").fullPath), "loop_points", List[
                        [36915, 39648, ],
                    ],
                ]), "87", Dictionary.newFrom([
                    "midi", "87", "duration", 2.9604535147392292, "frames", 130556, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.87.Viola.arco.sulA.mf.C6A6.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.87.Viola.arco.sulA.mf.C6A6.mono.wav").fullPath), "loop_points", List[
                        [48757, 49253, ],
                    ],
                ]), "77", Dictionary.newFrom([
                    "midi", "77", "duration", 3.1293197278911564, "frames", 138003, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.77.Viola.arco.sulA.mf.C5B5.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.77.Viola.arco.sulA.mf.C5B5.mono.wav").fullPath), "loop_points", List[
                        [69783, 71614, ],
                    ],
                ]), "88", Dictionary.newFrom([
                    "midi", "88", "duration", 3.1285260770975056, "frames", 137968, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.88.Viola.arco.sulA.mf.C6A6.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.88.Viola.arco.sulA.mf.C6A6.mono.wav").fullPath), "loop_points", List[
                        [68414, 69981, ],
                    ],
                ]), "72", Dictionary.newFrom([
                    "midi", "72", "duration", 3.986235827664399, "frames", 175793, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.72.Viola.arco.sulA.mf.C5B5.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.72.Viola.arco.sulA.mf.C5B5.mono.wav").fullPath), "loop_points", List[
                        [19208, 22242, ],
                    ],
                ]), "70", Dictionary.newFrom([
                    "midi", "70", "duration", 3.1931065759637187, "frames", 140816, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.70.Viola.arco.sulA.mf.A4B4.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.70.Viola.arco.sulA.mf.A4B4.mono.wav").fullPath), "loop_points", List[
                        [53959, 55853, ], [55457, 57351, ], [66085, 68642, ],
                    ],
                ]), "80", Dictionary.newFrom([
                    "midi", "80", "duration", 3.4387074829931974, "frames", 151647, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.80.Viola.arco.sulA.mf.C5B5.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.80.Viola.arco.sulA.mf.C5B5.mono.wav").fullPath), "loop_points", List[
                        [92825, 95431, ],
                    ],
                ]), "84", Dictionary.newFrom([
                    "midi", "84", "duration", 3.2626303854875283, "frames", 143882, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.84.Viola.arco.sulA.mf.C6A6.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.84.Viola.arco.sulA.mf.C6A6.mono.wav").fullPath), "loop_points", List[
                        [29249, 30886, ],
                    ],
                ]), "89", Dictionary.newFrom([
                    "midi", "89", "duration", 2.9065986394557823, "frames", 128181, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.89.Viola.arco.sulA.mf.C6A6.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.89.Viola.arco.sulA.mf.C6A6.mono.wav").fullPath), "loop_points", List[
                        [77314, 79967, ],
                    ],
                ]), "75", Dictionary.newFrom([
                    "midi", "75", "duration", 3.2319727891156464, "frames", 142530, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.75.Viola.arco.sulA.mf.C5B5.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.75.Viola.arco.sulA.mf.C5B5.mono.wav").fullPath), "loop_points", List[
                        [81859, 84054, ],
                    ],
                ]), "90", Dictionary.newFrom([
                    "midi", "90", "duration", 3.4854648526077097, "frames", 153709, "pitched", True, "dynamic_name", "mf", "dynamic_id", 1, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.90.Viola.arco.sulA.mf.C6A6.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.90.Viola.arco.sulA.mf.C6A6.mono.wav").fullPath), "loop_points", List[
                        [28981, 29963, ],
                    ],
                ]),
            ]),
        ]), "ff", Dictionary.newFrom([
            "c", Dictionary.newFrom([
                "48", Dictionary.newFrom([
                    "midi", "48", "duration", 3.8758049886621313, "frames", 170923, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.48.Viola.arco.sulC.ff.C3B3.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.48.Viola.arco.sulC.ff.C3B3.mono.wav").fullPath), "loop_points", List[
                        [56593, 59287, ], [56593, 59287, ], [63914, 66610, ], [63914, 66610, ], [69692, 72388, ],
                    ],
                ]), "63", Dictionary.newFrom([
                    "midi", "63", "duration", 2.4226303854875284, "frames", 106838, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.63.Viola.arco.sulC.ff.C4C5.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.63.Viola.arco.sulC.ff.C4C5.mono.wav").fullPath), "loop_points", List[
                        [40722, 44261, ],
                    ],
                ]), "49", Dictionary.newFrom([
                    "midi", "49", "duration", 3.028027210884354, "frames", 133536, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.49.Viola.arco.sulC.ff.C3B3.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.49.Viola.arco.sulC.ff.C3B3.mono.wav").fullPath), "loop_points", List[
                        [69222, 73358, ],
                    ],
                ]), "56", Dictionary.newFrom([
                    "midi", "56", "duration", 3.2011337868480725, "frames", 141170, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.56.Viola.arco.sulC.ff.C3B3.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.56.Viola.arco.sulC.ff.C3B3.mono.wav").fullPath), "loop_points", List[
                        [20373, 21864, ],
                    ],
                ]), "60", Dictionary.newFrom([
                    "midi", "60", "duration", 3.43437641723356, "frames", 151456, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.60.Viola.arco.sulC.ff.C4C5.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.60.Viola.arco.sulC.ff.C4C5.mono.wav").fullPath), "loop_points", List[
                        [57140, 59166, ], [64903, 66758, ],
                    ],
                ]), "66", Dictionary.newFrom([
                    "midi", "66", "duration", 2.591451247165533, "frames", 114283, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.66.Viola.arco.sulC.ff.C4C5.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.66.Viola.arco.sulC.ff.C4C5.mono.wav").fullPath), "loop_points", List[
                        [56227, 61014, ],
                    ],
                ]), "50", Dictionary.newFrom([
                    "midi", "50", "duration", 3.0048072562358277, "frames", 132512, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.50.Viola.arco.sulC.ff.C3B3.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.50.Viola.arco.sulC.ff.C3B3.mono.wav").fullPath), "loop_points", List[
                        [48446, 54741, ], [48747, 55043, ],
                    ],
                ]), "51", Dictionary.newFrom([
                    "midi", "51", "duration", 2.800861678004535, "frames", 123518, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.51.Viola.arco.sulC.ff.C3B3.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.51.Viola.arco.sulC.ff.C3B3.mono.wav").fullPath), "loop_points", List[
                        [37516, 40641, ],
                    ],
                ]), "57", Dictionary.newFrom([
                    "midi", "57", "duration", 2.9378684807256237, "frames", 129560, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.57.Viola.arco.sulC.ff.C3B3.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.57.Viola.arco.sulC.ff.C3B3.mono.wav").fullPath), "loop_points", List[
                        [33605, 41608, ],
                    ],
                ]), "61", Dictionary.newFrom([
                    "midi", "61", "duration", 2.5693650793650793, "frames", 113309, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.61.Viola.arco.sulC.ff.C4C5.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.61.Viola.arco.sulC.ff.C4C5.mono.wav").fullPath), "loop_points", List[
                        [43060, 46239, ], [43536, 46715, ],
                    ],
                ]), "64", Dictionary.newFrom([
                    "midi", "64", "duration", 2.852448979591837, "frames", 125793, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.64.Viola.arco.sulC.ff.C4C5.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.64.Viola.arco.sulC.ff.C4C5.mono.wav").fullPath), "loop_points", List[
                        [47716, 49587, ],
                    ],
                ]), "69", Dictionary.newFrom([
                    "midi", "69", "duration", 2.6123356009070293, "frames", 115204, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.69.Viola.arco.sulC.ff.C4C5.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.69.Viola.arco.sulC.ff.C4C5.mono.wav").fullPath), "loop_points", List[
                        [37771, 41084, ],
                    ],
                ]), "71", Dictionary.newFrom([
                    "midi", "71", "duration", 2.2457596371882085, "frames", 99038, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.71.Viola.arco.sulC.ff.C4C5.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.71.Viola.arco.sulC.ff.C4C5.mono.wav").fullPath), "loop_points", List[
                        [45173, 46072, ],
                    ],
                ]), "52", Dictionary.newFrom([
                    "midi", "52", "duration", 2.9663492063492063, "frames", 130816, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.52.Viola.arco.sulC.ff.C3B3.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.52.Viola.arco.sulC.ff.C3B3.mono.wav").fullPath), "loop_points", List[
                        [34423, 36296, ],
                    ],
                ]), "67", Dictionary.newFrom([
                    "midi", "67", "duration", 2.27297052154195, "frames", 100238, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.67.Viola.arco.sulC.ff.C4C5.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.67.Viola.arco.sulC.ff.C4C5.mono.wav").fullPath), "loop_points", List[
                        [20194, 22444, ],
                    ],
                ]), "53", Dictionary.newFrom([
                    "midi", "53", "duration", 3.114784580498866, "frames", 137362, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.53.Viola.arco.sulC.ff.C3B3.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.53.Viola.arco.sulC.ff.C3B3.mono.wav").fullPath), "loop_points", List[
                        [28609, 32646, ],
                    ],
                ]), "58", Dictionary.newFrom([
                    "midi", "58", "duration", 3.379206349206349, "frames", 149023, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.58.Viola.arco.sulC.ff.C3B3.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.58.Viola.arco.sulC.ff.C3B3.mono.wav").fullPath), "loop_points", List[
                        [51613, 58992, ],
                    ],
                ]), "62", Dictionary.newFrom([
                    "midi", "62", "duration", 3.2260090702947846, "frames", 142267, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.62.Viola.arco.sulC.ff.C4C5.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.62.Viola.arco.sulC.ff.C4C5.mono.wav").fullPath), "loop_points", List[
                        [81621, 82676, ],
                    ],
                ]), "54", Dictionary.newFrom([
                    "midi", "54", "duration", 3.082358276643991, "frames", 135932, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.54.Viola.arco.sulC.ff.C3B3.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.54.Viola.arco.sulC.ff.C3B3.mono.wav").fullPath), "loop_points", List[
                        [51506, 54130, ],
                    ],
                ]), "65", Dictionary.newFrom([
                    "midi", "65", "duration", 2.8561224489795918, "frames", 125955, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.65.Viola.arco.sulC.ff.C4C5.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.65.Viola.arco.sulC.ff.C4C5.mono.wav").fullPath), "loop_points", List[
                        [74991, 76883, ],
                    ],
                ]), "72", Dictionary.newFrom([
                    "midi", "72", "duration", 2.318548752834467, "frames", 102248, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.72.Viola.arco.sulC.ff.C4C5.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.72.Viola.arco.sulC.ff.C4C5.mono.wav").fullPath), "loop_points", List[
                        [16167, 17684, ],
                    ],
                ]), "55", Dictionary.newFrom([
                    "midi", "55", "duration", 3.267823129251701, "frames", 144111, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.55.Viola.arco.sulC.ff.C3B3.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.55.Viola.arco.sulC.ff.C3B3.mono.wav").fullPath), "loop_points", List[
                        [64880, 70951, ],
                    ],
                ]), "59", Dictionary.newFrom([
                    "midi", "59", "duration", 3.0871655328798187, "frames", 136144, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.59.Viola.arco.sulC.ff.C3B3.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.59.Viola.arco.sulC.ff.C3B3.mono.wav").fullPath), "loop_points", List[
                        [36994, 42513, ],
                    ],
                ]), "68", Dictionary.newFrom([
                    "midi", "68", "duration", 2.2773015873015874, "frames", 100429, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.68.Viola.arco.sulC.ff.C4C5.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.68.Viola.arco.sulC.ff.C4C5.mono.wav").fullPath), "loop_points", List[
                        [18110, 19807, ], [61107, 64111, ],
                    ],
                ]), "70", Dictionary.newFrom([
                    "midi", "70", "duration", 2.115827664399093, "frames", 93308, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.70.Viola.arco.sulC.ff.C4C5.mono.wav").fullPath, "string_name", "C", "string_id", 0, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.70.Viola.arco.sulC.ff.C4C5.mono.wav").fullPath), "loop_points", List[
                        [50197, 51238, ],
                    ],
                ]),
            ]), "g", Dictionary.newFrom([
                "55", Dictionary.newFrom([
                    "midi", "55", "duration", 6.26795918367347, "frames", 276417, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.55.Viola.arco.sulG.ff.G3B3.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.55.Viola.arco.sulG.ff.G3B3.mono.wav").fullPath), "loop_points", List[
                        [82283, 87003, ],
                    ],
                ]), "59", Dictionary.newFrom([
                    "midi", "59", "duration", 3.478684807256236, "frames", 153410, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.59.Viola.arco.sulG.ff.G3B3.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.59.Viola.arco.sulG.ff.G3B3.mono.wav").fullPath), "loop_points", List[
                        [47674, 50169, ], [92002, 94495, ],
                    ],
                ]), "65", Dictionary.newFrom([
                    "midi", "65", "duration", 2.8519501133786846, "frames", 125771, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.65.Viola.arco.sulG.ff.C4B4.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.65.Viola.arco.sulG.ff.C4B4.mono.wav").fullPath), "loop_points", List[
                        [75777, 80830, ],
                    ],
                ]), "72", Dictionary.newFrom([
                    "midi", "72", "duration", 2.5383219954648526, "frames", 111940, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.72.Viola.arco.sulG.ff.C5G5.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.72.Viola.arco.sulG.ff.C5G5.mono.wav").fullPath), "loop_points", List[
                        [45874, 47303, ],
                    ],
                ]), "68", Dictionary.newFrom([
                    "midi", "68", "duration", 2.668208616780045, "frames", 117668, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.68.Viola.arco.sulG.ff.C4B4.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.68.Viola.arco.sulG.ff.C4B4.mono.wav").fullPath), "loop_points", List[
                        [75712, 76668, ],
                    ],
                ]), "70", Dictionary.newFrom([
                    "midi", "70", "duration", 2.6566666666666667, "frames", 117159, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.70.Viola.arco.sulG.ff.C4B4.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.70.Viola.arco.sulG.ff.C4B4.mono.wav").fullPath), "loop_points", List[
                        [17385, 18896, ], [17951, 19464, ], [60882, 62393, ],
                    ],
                ]), "75", Dictionary.newFrom([
                    "midi", "75", "duration", 2.619342403628118, "frames", 115513, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.75.Viola.arco.sulG.ff.C5G5.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.75.Viola.arco.sulG.ff.C5G5.mono.wav").fullPath), "loop_points", List[
                        [54190, 54897, ], [62890, 63526, ],
                    ],
                ]), "56", Dictionary.newFrom([
                    "midi", "56", "duration", 3.2843083900226757, "frames", 144838, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.56.Viola.arco.sulG.ff.G3B3.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.56.Viola.arco.sulG.ff.G3B3.mono.wav").fullPath), "loop_points", List[
                        [46776, 51449, ],
                    ],
                ]), "60", Dictionary.newFrom([
                    "midi", "60", "duration", 3.787074829931973, "frames", 167010, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.60.Viola.arco.sulG.ff.C4B4.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.60.Viola.arco.sulG.ff.C4B4.mono.wav").fullPath), "loop_points", List[
                        [76527, 83271, ],
                    ],
                ]), "63", Dictionary.newFrom([
                    "midi", "63", "duration", 2.7395238095238095, "frames", 120813, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.63.Viola.arco.sulG.ff.C4B4.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.63.Viola.arco.sulG.ff.C4B4.mono.wav").fullPath), "loop_points", List[
                        [24754, 27308, ],
                    ],
                ]), "78", Dictionary.newFrom([
                    "midi", "78", "duration", 2.4412244897959186, "frames", 107658, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.78.Viola.arco.sulG.ff.C5G5.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.78.Viola.arco.sulG.ff.C5G5.mono.wav").fullPath), "loop_points", List[
                        [35152, 38128, ],
                    ],
                ]), "66", Dictionary.newFrom([
                    "midi", "66", "duration", 2.856485260770975, "frames", 125971, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.66.Viola.arco.sulG.ff.C4B4.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.66.Viola.arco.sulG.ff.C4B4.mono.wav").fullPath), "loop_points", List[
                        [82020, 83334, ],
                    ],
                ]), "73", Dictionary.newFrom([
                    "midi", "73", "duration", 2.412063492063492, "frames", 106372, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.73.Viola.arco.sulG.ff.C5G5.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.73.Viola.arco.sulG.ff.C5G5.mono.wav").fullPath), "loop_points", List[
                        [29074, 31780, ],
                    ],
                ]), "57", Dictionary.newFrom([
                    "midi", "57", "duration", 3.432312925170068, "frames", 151365, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.57.Viola.arco.sulG.ff.G3B3.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.57.Viola.arco.sulG.ff.G3B3.mono.wav").fullPath), "loop_points", List[
                        [62372, 68371, ], [62719, 68718, ], [63372, 69371, ], [64119, 70118, ], [64171, 70368, ], [64372, 70572, ],
                    ],
                ]), "61", Dictionary.newFrom([
                    "midi", "61", "duration", 2.807437641723356, "frames", 123808, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.61.Viola.arco.sulG.ff.C4B4.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.61.Viola.arco.sulG.ff.C4B4.mono.wav").fullPath), "loop_points", List[
                        [64488, 66238, ],
                    ],
                ]), "76", Dictionary.newFrom([
                    "midi", "76", "duration", 2.795238095238095, "frames", 123270, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.76.Viola.arco.sulG.ff.C5G5.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.76.Viola.arco.sulG.ff.C5G5.mono.wav").fullPath), "loop_points", List[
                        [42133, 44471, ],
                    ],
                ]), "71", Dictionary.newFrom([
                    "midi", "71", "duration", 2.6005895691609977, "frames", 114686, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.71.Viola.arco.sulG.ff.C4B4.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.71.Viola.arco.sulG.ff.C4B4.mono.wav").fullPath), "loop_points", List[
                        [75517, 77926, ], [75655, 78064, ],
                    ],
                ]), "64", Dictionary.newFrom([
                    "midi", "64", "duration", 2.93859410430839, "frames", 129592, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.64.Viola.arco.sulG.ff.C4B4.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.64.Viola.arco.sulG.ff.C4B4.mono.wav").fullPath), "loop_points", List[
                        [86169, 87783, ],
                    ],
                ]), "69", Dictionary.newFrom([
                    "midi", "69", "duration", 3.2380045351473923, "frames", 142796, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.69.Viola.arco.sulG.ff.C4B4.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.69.Viola.arco.sulG.ff.C4B4.mono.wav").fullPath), "loop_points", List[
                        [56102, 59699, ],
                    ],
                ]), "79", Dictionary.newFrom([
                    "midi", "79", "duration", 2.9812471655328796, "frames", 131473, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.79.Viola.arco.sulG.ff.C5G5.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.79.Viola.arco.sulG.ff.C5G5.mono.wav").fullPath), "loop_points", List[
                        [23031, 24156, ],
                    ],
                ]), "58", Dictionary.newFrom([
                    "midi", "58", "duration", 3.844784580498866, "frames", 169555, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.58.Viola.arco.sulG.ff.G3B3.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.58.Viola.arco.sulG.ff.G3B3.mono.wav").fullPath), "loop_points", List[
                        [86977, 92439, ],
                    ],
                ]), "67", Dictionary.newFrom([
                    "midi", "67", "duration", 3.60421768707483, "frames", 158946, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.67.Viola.arco.sulG.ff.C4B4.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.67.Viola.arco.sulG.ff.C4B4.mono.wav").fullPath), "loop_points", List[
                        [87421, 88552, ], [88468, 89596, ], [100019, 100585, ],
                    ],
                ]), "74", Dictionary.newFrom([
                    "midi", "74", "duration", 2.7168027210884356, "frames", 119811, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.74.Viola.arco.sulG.ff.C5G5.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.74.Viola.arco.sulG.ff.C5G5.mono.wav").fullPath), "loop_points", List[
                        [40583, 42913, ],
                    ],
                ]), "62", Dictionary.newFrom([
                    "midi", "62", "duration", 2.7638775510204083, "frames", 121887, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.62.Viola.arco.sulG.ff.C4B4.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.62.Viola.arco.sulG.ff.C4B4.mono.wav").fullPath), "loop_points", List[
                        [54557, 59523, ],
                    ],
                ]), "77", Dictionary.newFrom([
                    "midi", "77", "duration", 2.7062131519274377, "frames", 119344, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.77.Viola.arco.sulG.ff.C5G5.mono.wav").fullPath, "string_name", "G", "string_id", 1, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.77.Viola.arco.sulG.ff.C5G5.mono.wav").fullPath), "loop_points", List[
                        [57914, 60429, ],
                    ],
                ]),
            ]), "d", Dictionary.newFrom([
                "68", Dictionary.newFrom([
                    "midi", "68", "duration", 3.251451247165533, "frames", 143389, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.68.Viola.arco.sulD.ff.D4B4.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.68.Viola.arco.sulD.ff.D4B4.mono.wav").fullPath), "loop_points", List[
                        [26216, 28343, ],
                    ],
                ]), "70", Dictionary.newFrom([
                    "midi", "70", "duration", 3.486190476190476, "frames", 153741, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.70.Viola.arco.sulD.ff.D4B4.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.70.Viola.arco.sulD.ff.D4B4.mono.wav").fullPath), "loop_points", List[
                        [84575, 88349, ], [85689, 89464, ],
                    ],
                ]), "75", Dictionary.newFrom([
                    "midi", "75", "duration", 2.839863945578231, "frames", 125238, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.75.Viola.arco.sulD.ff.C5B5.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.75.Viola.arco.sulD.ff.C5B5.mono.wav").fullPath), "loop_points", List[
                        [56294, 58567, ],
                    ],
                ]), "63", Dictionary.newFrom([
                    "midi", "63", "duration", 3.3536507936507935, "frames", 147896, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.63.Viola.arco.sulD.ff.D4B4.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.63.Viola.arco.sulD.ff.D4B4.mono.wav").fullPath), "loop_points", List[
                        [66332, 70012, ],
                    ],
                ]), "78", Dictionary.newFrom([
                    "midi", "78", "duration", 2.69875283446712, "frames", 119015, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.78.Viola.arco.sulD.ff.C5B5.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.78.Viola.arco.sulD.ff.C5B5.mono.wav").fullPath), "loop_points", List[
                        [72353, 73665, ],
                    ],
                ]), "81", Dictionary.newFrom([
                    "midi", "81", "duration", 2.460521541950113, "frames", 108509, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.81.Viola.arco.sulD.ff.C5B5.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.81.Viola.arco.sulD.ff.C5B5.mono.wav").fullPath), "loop_points", List[
                        [17472, 21130, ],
                    ],
                ]), "85", Dictionary.newFrom([
                    "midi", "85", "duration", 3.786734693877551, "frames", 166995, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.85.Viola.arco.sulD.ff.C6D6.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.85.Viola.arco.sulD.ff.C6D6.mono.wav").fullPath), "loop_points", List[
                        [40042, 43409, ],
                    ],
                ]), "66", Dictionary.newFrom([
                    "midi", "66", "duration", 3.290408163265306, "frames", 145107, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.66.Viola.arco.sulD.ff.D4B4.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.66.Viola.arco.sulD.ff.D4B4.mono.wav").fullPath), "loop_points", List[
                        [71714, 76365, ], [72907, 77558, ],
                    ],
                ]), "73", Dictionary.newFrom([
                    "midi", "73", "duration", 2.9434467120181407, "frames", 129806, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.73.Viola.arco.sulD.ff.C5B5.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.73.Viola.arco.sulD.ff.C5B5.mono.wav").fullPath), "loop_points", List[
                        [89397, 92257, ],
                    ],
                ]), "76", Dictionary.newFrom([
                    "midi", "76", "duration", 3.2724263038548753, "frames", 144314, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.76.Viola.arco.sulD.ff.C5B5.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.76.Viola.arco.sulD.ff.C5B5.mono.wav").fullPath), "loop_points", List[
                        [41170, 43727, ], [41910, 44468, ],
                    ],
                ]), "82", Dictionary.newFrom([
                    "midi", "82", "duration", 2.5827437641723354, "frames", 113899, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.82.Viola.arco.sulD.ff.C5B5.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.82.Viola.arco.sulD.ff.C5B5.mono.wav").fullPath), "loop_points", List[
                        [44410, 47151, ],
                    ],
                ]), "86", Dictionary.newFrom([
                    "midi", "86", "duration", 3.661700680272109, "frames", 161481, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.86.Viola.arco.sulD.ff.C6D6.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.86.Viola.arco.sulD.ff.C6D6.mono.wav").fullPath), "loop_points", List[
                        [72182, 74843, ],
                    ],
                ]), "71", Dictionary.newFrom([
                    "midi", "71", "duration", 3.0250793650793653, "frames", 133406, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.71.Viola.arco.sulD.ff.D4B4.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.71.Viola.arco.sulD.ff.D4B4.mono.wav").fullPath), "loop_points", List[
                        [30011, 33931, ],
                    ],
                ]), "64", Dictionary.newFrom([
                    "midi", "64", "duration", 3.3865532879818594, "frames", 149347, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.64.Viola.arco.sulD.ff.D4B4.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.64.Viola.arco.sulD.ff.D4B4.mono.wav").fullPath), "loop_points", List[
                        [56364, 61439, ],
                    ],
                ]), "69", Dictionary.newFrom([
                    "midi", "69", "duration", 2.9570975056689344, "frames", 130408, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.69.Viola.arco.sulD.ff.D4B4.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.69.Viola.arco.sulD.ff.D4B4.mono.wav").fullPath), "loop_points", List[
                        [38160, 41461, ],
                    ],
                ]), "79", Dictionary.newFrom([
                    "midi", "79", "duration", 3.4920861678004536, "frames", 154001, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.79.Viola.arco.sulD.ff.C5B5.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.79.Viola.arco.sulD.ff.C5B5.mono.wav").fullPath), "loop_points", List[
                        [90599, 92286, ],
                    ],
                ]), "67", Dictionary.newFrom([
                    "midi", "67", "duration", 3.1722902494331064, "frames", 139898, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.67.Viola.arco.sulD.ff.D4B4.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.67.Viola.arco.sulD.ff.D4B4.mono.wav").fullPath), "loop_points", List[
                        [69103, 70792, ],
                    ],
                ]), "74", Dictionary.newFrom([
                    "midi", "74", "duration", 2.9773696145124715, "frames", 131302, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.74.Viola.arco.sulD.ff.C5B5.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.74.Viola.arco.sulD.ff.C5B5.mono.wav").fullPath), "loop_points", List[
                        [15027, 18162, ],
                    ],
                ]), "83", Dictionary.newFrom([
                    "midi", "83", "duration", 2.5750566893424036, "frames", 113560, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.83.Viola.arco.sulD.ff.C5B5.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.83.Viola.arco.sulD.ff.C5B5.mono.wav").fullPath), "loop_points", List[
                        [67988, 75562, ],
                    ],
                ]), "62", Dictionary.newFrom([
                    "midi", "62", "duration", 3.800340136054422, "frames", 167595, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.62.Viola.arco.sulD.ff.D4B4.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.62.Viola.arco.sulD.ff.D4B4.mono.wav").fullPath), "loop_points", List[
                        [74271, 78021, ],
                    ],
                ]), "77", Dictionary.newFrom([
                    "midi", "77", "duration", 2.959591836734694, "frames", 130518, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.77.Viola.arco.sulD.ff.C5B5.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.77.Viola.arco.sulD.ff.C5B5.mono.wav").fullPath), "loop_points", List[
                        [63934, 66387, ],
                    ],
                ]), "65", Dictionary.newFrom([
                    "midi", "65", "duration", 3.3760997732426303, "frames", 148886, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.65.Viola.arco.sulD.ff.D4B4.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.65.Viola.arco.sulD.ff.D4B4.mono.wav").fullPath), "loop_points", List[
                        [76073, 80240, ],
                    ],
                ]), "72", Dictionary.newFrom([
                    "midi", "72", "duration", 3.305986394557823, "frames", 145794, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.72.Viola.arco.sulD.ff.C5B5.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.72.Viola.arco.sulD.ff.C5B5.mono.wav").fullPath), "loop_points", List[
                        [48817, 49742, ],
                    ],
                ]), "80", Dictionary.newFrom([
                    "midi", "80", "duration", 2.588798185941043, "frames", 114166, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.80.Viola.arco.sulD.ff.C5B5.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.80.Viola.arco.sulD.ff.C5B5.mono.wav").fullPath), "loop_points", List[
                        [17906, 20013, ], [17971, 20078, ], [19235, 21979, ], [49872, 51989, ],
                    ],
                ]), "84", Dictionary.newFrom([
                    "midi", "84", "duration", 3.340861678004535, "frames", 147332, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.84.Viola.arco.sulD.ff.C6D6.mono.wav").fullPath, "string_name", "D", "string_id", 2, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.84.Viola.arco.sulD.ff.C6D6.mono.wav").fullPath), "loop_points", List[
                        [57548, 62224, ],
                    ],
                ]),
            ]), "a", Dictionary.newFrom([
                "78", Dictionary.newFrom([
                    "midi", "78", "duration", 2.584263038548753, "frames", 113966, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.78.Viola.arco.sulA.ff.C5B5.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.78.Viola.arco.sulA.ff.C5B5.mono.wav").fullPath), "loop_points", List[
                        [40811, 42897, ],
                    ],
                ]), "81", Dictionary.newFrom([
                    "midi", "81", "duration", 2.2901587301587303, "frames", 100996, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.81.Viola.arco.sulA.ff.C5B5.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.81.Viola.arco.sulA.ff.C5B5.mono.wav").fullPath), "loop_points", List[
                        [31541, 33197, ],
                    ],
                ]), "85", Dictionary.newFrom([
                    "midi", "85", "duration", 2.507981859410431, "frames", 110602, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.85.Viola.arco.sulA.ff.C6A6.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.85.Viola.arco.sulA.ff.C6A6.mono.wav").fullPath), "loop_points", List[
                        [49568, 52711, ],
                    ],
                ]), "91", Dictionary.newFrom([
                    "midi", "91", "duration", 2.357369614512472, "frames", 103960, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.91.Viola.arco.sulA.ff.C6A6.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.91.Viola.arco.sulA.ff.C6A6.mono.wav").fullPath), "loop_points", List[
                        [39020, 39580, ],
                    ],
                ]), "73", Dictionary.newFrom([
                    "midi", "73", "duration", 2.545487528344671, "frames", 112256, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.73.Viola.arco.sulA.ff.C5B5.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.73.Viola.arco.sulA.ff.C5B5.mono.wav").fullPath), "loop_points", List[
                        [28484, 31591, ],
                    ],
                ]), "92", Dictionary.newFrom([
                    "midi", "92", "duration", 2.4668707482993195, "frames", 108789, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.92.Viola.arco.sulA.ff.C6A6.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.92.Viola.arco.sulA.ff.C6A6.mono.wav").fullPath), "loop_points", List[
                        [46672, 48398, ],
                    ],
                ]), "69", Dictionary.newFrom([
                    "midi", "69", "duration", 2.8462358276643993, "frames", 125519, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.69.Viola.arco.sulA.ff.A4B4.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.69.Viola.arco.sulA.ff.A4B4.mono.wav").fullPath), "loop_points", List[
                        [19108, 19811, ],
                    ],
                ]), "71", Dictionary.newFrom([
                    "midi", "71", "duration", 2.528458049886621, "frames", 111505, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.71.Viola.arco.sulA.ff.A4B4.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.71.Viola.arco.sulA.ff.A4B4.mono.wav").fullPath), "loop_points", List[
                        [40819, 43232, ],
                    ],
                ]), "76", Dictionary.newFrom([
                    "midi", "76", "duration", 2.9289569160997733, "frames", 129167, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.76.Viola.arco.sulA.ff.C5B5.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.76.Viola.arco.sulA.ff.C5B5.mono.wav").fullPath), "loop_points", List[
                        [67776, 69989, ],
                    ],
                ]), "82", Dictionary.newFrom([
                    "midi", "82", "duration", 2.2376643990929703, "frames", 98681, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.82.Viola.arco.sulA.ff.C5B5.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.82.Viola.arco.sulA.ff.C5B5.mono.wav").fullPath), "loop_points", List[
                        [52016, 54095, ],
                    ],
                ]), "86", Dictionary.newFrom([
                    "midi", "86", "duration", 2.79984126984127, "frames", 123473, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.86.Viola.arco.sulA.ff.C6A6.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.86.Viola.arco.sulA.ff.C6A6.mono.wav").fullPath), "loop_points", List[
                        [56576, 59280, ],
                    ],
                ]), "93", Dictionary.newFrom([
                    "midi", "93", "duration", 2.3740362811791385, "frames", 104695, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.93.Viola.arco.sulA.ff.C6A6.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.93.Viola.arco.sulA.ff.C6A6.mono.wav").fullPath), "loop_points", List[
                        [64003, 64681, ],
                    ],
                ]), "79", Dictionary.newFrom([
                    "midi", "79", "duration", 2.808480725623583, "frames", 123854, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.79.Viola.arco.sulA.ff.C5B5.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.79.Viola.arco.sulA.ff.C5B5.mono.wav").fullPath), "loop_points", List[
                        [19075, 19861, ], [22867, 23991, ],
                    ],
                ]), "74", Dictionary.newFrom([
                    "midi", "74", "duration", 3.0686167800453514, "frames", 135326, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.74.Viola.arco.sulA.ff.C5B5.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.74.Viola.arco.sulA.ff.C5B5.mono.wav").fullPath), "loop_points", List[
                        [30235, 33090, ],
                    ],
                ]), "83", Dictionary.newFrom([
                    "midi", "83", "duration", 2.3423582766439908, "frames", 103298, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.83.Viola.arco.sulA.ff.C5B5.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.83.Viola.arco.sulA.ff.C5B5.mono.wav").fullPath), "loop_points", List[
                        [15297, 17574, ], [15297, 17618, ],
                    ],
                ]), "87", Dictionary.newFrom([
                    "midi", "87", "duration", 2.580136054421769, "frames", 113784, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.87.Viola.arco.sulA.ff.C6A6.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.87.Viola.arco.sulA.ff.C6A6.mono.wav").fullPath), "loop_points", List[
                        [14753, 15929, ],
                    ],
                ]), "77", Dictionary.newFrom([
                    "midi", "77", "duration", 2.23562358276644, "frames", 98591, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.77.Viola.arco.sulA.ff.C5B5.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.77.Viola.arco.sulA.ff.C5B5.mono.wav").fullPath), "loop_points", List[
                        [15220, 18507, ], [15220, 18507, ],
                    ],
                ]), "88", Dictionary.newFrom([
                    "midi", "88", "duration", 2.4323809523809525, "frames", 107268, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.88.Viola.arco.sulA.ff.C6A6.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.88.Viola.arco.sulA.ff.C6A6.mono.wav").fullPath), "loop_points", List[
                        [65268, 68678, ],
                    ],
                ]), "72", Dictionary.newFrom([
                    "midi", "72", "duration", 3.510498866213152, "frames", 154813, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.72.Viola.arco.sulA.ff.C5B5.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.72.Viola.arco.sulA.ff.C5B5.mono.wav").fullPath), "loop_points", List[
                        [79857, 82979, ],
                    ],
                ]), "70", Dictionary.newFrom([
                    "midi", "70", "duration", 2.6068253968253967, "frames", 114961, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.70.Viola.arco.sulA.ff.A4B4.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.70.Viola.arco.sulA.ff.A4B4.mono.wav").fullPath), "loop_points", List[
                        [31466, 34320, ],
                    ],
                ]), "80", Dictionary.newFrom([
                    "midi", "80", "duration", 2.540090702947846, "frames", 112018, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.80.Viola.arco.sulA.ff.C5B5.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.80.Viola.arco.sulA.ff.C5B5.mono.wav").fullPath), "loop_points", List[
                        [31975, 34091, ], [32129, 34246, ], [32288, 34405, ], [32342, 34458, ], [32448, 34564, ], [61568, 62997, ],
                    ],
                ]), "84", Dictionary.newFrom([
                    "midi", "84", "duration", 2.315873015873016, "frames", 102130, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.84.Viola.arco.sulA.ff.C6A6.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.84.Viola.arco.sulA.ff.C6A6.mono.wav").fullPath), "loop_points", List[
                        [15434, 17460, ],
                    ],
                ]), "89", Dictionary.newFrom([
                    "midi", "89", "duration", 2.4522448979591838, "frames", 108144, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.89.Viola.arco.sulA.ff.C6A6.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.89.Viola.arco.sulA.ff.C6A6.mono.wav").fullPath), "loop_points", List[
                        [46334, 46744, ],
                    ],
                ]), "75", Dictionary.newFrom([
                    "midi", "75", "duration", 2.2423356009070297, "frames", 98887, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.75.Viola.arco.sulA.ff.C5B5.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.75.Viola.arco.sulA.ff.C5B5.mono.wav").fullPath), "loop_points", List[
                        [15100, 17869, ], [34501, 37340, ], [34856, 37624, ],
                    ],
                ]), "90", Dictionary.newFrom([
                    "midi", "90", "duration", 2.514172335600907, "frames", 110875, "pitched", True, "dynamic_name", "ff", "dynamic_id", 3, "instrument_type", "viola", "path", PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.90.Viola.arco.sulA.ff.C6A6.mono.wav").fullPath, "string_name", "A", "string_id", 3, "buffer", Buffer.read(s, PathName(~root_sample_dir ++ "samples/Viola.arco.mono.2444.1/sample.90.Viola.arco.sulA.ff.C6A6.mono.wav").fullPath), "loop_points", List[
                        [25934, 27210, ],
                    ],
                ]),
            ]),
        ]),
    ]),
]);