Synth(\granulator_x, [
    \bufs, [
        ~samples["tenortrombone"]["ff"]["48"]["buffer"],
        ~samples["basstrombone"]["ff"]["48"]["buffer"],
        ~samples["bassclarinet"]["ff"]["48"]["buffer"],
        ~samples["tuba"]["ff"]["48"]["buffer"],
        ~samples["tenortrombone"]["ff"]["50"]["buffer"],
        ~samples["basstrombone"]["ff"]["50"]["buffer"],
        ~samples["bassclarinet"]["ff"]["43"]["buffer"],
        ~samples["tuba"]["ff"]["43"]["buffer"]
    ],
    \weights, 0.125!8,
    \density, 100,
    \dur, 0.1,
    \mul, 0.1
]);